apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: influx-qery-
  labels:
    workflows.argoproj.io/archive-strategy: "always"
  annotations:
    workflows.argoproj.io/description: |
      This is a simple hello world example.

spec:
  entrypoint: echotest
  templates:
  - name: echotest
    container:
      image: alpine
      command: ["sh", "-c"]
      args: ["echo", "hello kubernetes"]
